import { ArrowLeft } from 'lucide-react'

function Terms() {
  return (
    <div className="min-h-screen p-4">
      <div className="max-w-4xl mx-auto">
        <a href="/" className="inline-flex items-center gap-2 text-primary-600 hover:text-primary-700 mb-6">
          <ArrowLeft className="w-4 h-4" />
          Back to StreamBuddy
        </a>

        <div className="card">
          <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
          <div className="prose prose-slate max-w-none space-y-6 text-sm">
            <p className="text-gray-600">Last updated: March 16, 2026</p>

            <section>
              <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
              <p>
                By accessing and using StreamBuddy ("the Service"), you agree to be bound by these Terms of Service. 
                If you do not agree to these terms, please do not use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">2. Description of Service</h2>
              <p>
                StreamBuddy is an AI-powered co-host for live streaming that provides real-time voice interaction, 
                chat monitoring, and contextual responses using Google's Gemini Live API.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">3. YouTube Integration</h2>
              <p>
                StreamBuddy integrates with YouTube Live API to read chat messages. By connecting your YouTube account, 
                you authorize StreamBuddy to access your YouTube Live chat data. You can revoke this access at any time 
                through your Google Account settings.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">4. AI-Generated Content</h2>
              <p>
                The AI responses generated by StreamBuddy are powered by Google's Gemini Live API. While we strive for 
                accuracy and appropriateness, AI-generated content may occasionally be inaccurate, inappropriate, or 
                unexpected. You are responsible for monitoring and moderating AI responses during your streams.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">5. Limitation of Liability</h2>
              <p>
                StreamBuddy is provided "as is" without warranties of any kind. We are not liable for any damages 
                arising from your use of the Service, including but not limited to loss of data, revenue, or reputation.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">6. Service Availability</h2>
              <p>
                We do not guarantee uninterrupted or error-free operation of the Service. We reserve the right to 
                modify, suspend, or discontinue the Service at any time without notice.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">7. Changes to Terms</h2>
              <p>
                We reserve the right to modify these Terms of Service at any time. Continued use of the Service 
                after changes constitutes acceptance of the modified terms.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-3">8. Contact</h2>
              <p>
                For questions about these Terms of Service, please contact us at{' '}
                <a href="mailto:acedev02@gmail.com" className="text-primary-600 hover:underline">
                  acedev02@gmail.com
                </a>
              </p>
            </section>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Terms
